pipeline:
  browser: chromium
  browser_params:
    headless: false
  steps:
    - goto: http://80.191.255.65/
    - loop: "[1,990090345]"
      loop-key: city
      steps:
        - select: "#ContentPlaceHolder1_ddlCity"
          values: "{{ city }}"
          on-error: ignore
        - sleep: 100ms
        - loop: '{{ eval "JSON.stringify([...document.querySelectorAll(''#ContentPlaceHolder1_ddlArea > option'')].map((a) => a.getAttribute(''value'')))" }}'
          on-error: ignore
          steps:
            - goto: http://80.191.255.65/
            - click: "#ContentPlaceHolder1_rbIsAddress"
            - select: "#ContentPlaceHolder1_ddlCity"
              on-error: ignore
              values: "{{ city }}"
            - sleep: 100ms
            - select: "#ContentPlaceHolder1_ddlArea"
              on-error: ignore
              values: "{{ item }}"
            - eval: console.log('{{ city }},{{ item }}')
            - click: "#ContentPlaceHolder1_btnSearchOutage"
            - element: "#ContentPlaceHolder1_grdOutages"
              on-error: ignore
              mode: table
              set-var: result
