pipeline:
  browser: chromium
  # keep_running: 5m
  browser_params:
    headless: false
  vars:
    - name: page
      value: test
  steps:
    - goto: https://tools.admin.dornicafile.ir/test.html
    - if: |
        "{{ "156" | eval }}" is 156
      element: table
      mode: table
      set-var: result
