pipeline:
  browser: chromium
  keep_running: 5m
  browser_params:
    headless: false
    args:
      - "--start-maximized"
      - "--disable-blink-features=AutomationControlled"
      - "--no-sandbox"
      - "--disable-gpu"
      - "--disable-dev-shm-usage"
      - "--disable-web-security"
      - "--disable-features=IsolateOrigins,site-per-process"
      - "--disable-site-isolation-trials"
      - "--allow-running-insecure-content"
      - "--ignore-certificate-errors"
      - "--disable-infobars"
      - "--disable-breakpad"
      - "--disable-background-timer-throttling"
      - "--disable-renderer-backgrounding"
      - "--disable-backgrounding-occluded-windows"
      - "--disable-client-side-phishing-detection"
      - "--disable-hang-monitor"
      - "--disable-popup-blocking"
      - "--disable-prompt-on-repost"
      - "--disable-sync"
      - "--metrics-recording-only"
      - "--mute-audio"
      - "--password-store=basic"
      - "--use-mock-keychain"
      - "--disable-extensions"
      - "--no-default-browser-check"
    chromiumSandbox: false
    devtools: false
    handleSIGHUP: false
    handleSIGINT: false
    handleSIGTERM: false
    ignoreAllDefaultArgs: false
    slowMo: 50
    timeout: 60000
    tracesDir: "./traces"
    downloadsPath: "./downloads"
  steps:
    - goto: https://www.nic.ir/Login
    - click: "div > label > input[type=checkbox]"
    - screenshot: body
      screenshot_params:
        path: "./screenshot2.png"
