pipeline:
  browser: chromium
  keep_running: 5m
  browser_params:
    headless: true

  steps:
    - goto: https://bot.sannysoft.com/
    - screenshot: body
      screenshot_params:
        path: "./screenshot2.png"
