pipeline:
  browser: chromium
  # keep_running: 5m
  browser_params:
    headless: false
  steps:
    - goto: https://tools.admin.dornicafile.ir/test.html
    - element: table
      mode: table
      set-var: result
    - click: table225
      params:
        timeout: 1000
      on-error: print
