pipeline:
  browser: chromium
  # keep_running: 5m
  browser_params:
    headless: false
  vars:
    - name: page
      value: test
  steps:
    - goto: https://tools.admin.dornicafile.ir/test.html
    - table: table
      set-var: table
