version: 2

before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/FMotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/FMotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/FMotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/FMotalleb/go-tools/git.Branch={{.Branch}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

  - id: slim
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/FMotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/FMotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/FMotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/FMotalleb/go-tools/git.Branch={{.Branch}}"
    goos:
      - linux
    goarch:
      - amd64
    binary: scrapper-go
    skip: "archive"

dockers:
  - image_templates:
      - "ghcr.io/fmotalleb/scrapper-go:{{ .Version }}"
      - "ghcr.io/fmotalleb/scrapper-go:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - slim
    use: buildx

archives:
  - id: default
    builds:
      - default

release:
  github:
    owner: FMotalleb
    name: scrapper-go
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append

changelog:
  disable: true
